name: Run tests for pust-to-another-repo action

on: 
  workflow_dispatch:

jobs:
  run-tests:
    name: Run tests for pust-to-another-repo action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup test files and directory
        run: |
          mkdir -p test-dir
          echo $(date) > test-dir/date.txt
          echo "Another test file" > test-dir/content.txt

      - name: test for file as source input
        id: test-file-source
        uses: ./push-to-another-repo
        with:
          source: test-dir/date.txt
          destination_repo_name: gadaniyati/actions
          destination_branch: test-file
          access_key: ${{ secrets.ACCESS_KEY }}
      
      - name: test for output parameter commit hash
        env:
          COMMIT_HASH: ${{ steps.test-file-source.outputs.commit_hash }}
        run: echo "The SHA hash of the generated commit - $COMMIT_HASH"

      - name: test for directory as source input
        uses: ./push-to-another-repo
        with:
          source: test-dir
          destination_repo_name: gadaniyati/actions
          destination_branch: test-directory
          access_key: ${{ secrets.ACCESS_KEY }}

      - name: test for destination directory as output directory
        uses: ./push-to-another-repo
        with:
          source: test-dir
          destination_repo_name: gadaniyati/actions
          destination_directory: pushed-changes
          destination_branch: test-destination-directory
          access_key: ${{ secrets.ACCESS_KEY }}

      - name: test for nested destination directory as output directory
        uses: ./push-to-another-repo
        with:
          source: test-dir
          destination_repo_name: gadaniyati/actions
          destination_directory: pushed-changes/level-1
          destination_branch: test-nested-destination-directory
          access_key: ${{ secrets.ACCESS_KEY }}

      - name: test for delete content of destination directory
        uses: ./push-to-another-repo
        with:
          source: test-dir
          destination_repo_name: gadaniyati/actions
          destination_branch: test-delete-destination-content
          delete_destination_content: "true"
          access_key: ${{ secrets.ACCESS_KEY }}

      - name: test for different username and email
        uses: ./push-to-another-repo
        with:
          source: test-dir
          destination_repo_name: gadaniyati/actions
          destination_branch: test-username-email
          user_name: galaumang
          user_email: toumangg@gmail.com
          access_key: ${{ secrets.ACCESS_KEY }}

      - name: test for custom commit message
        uses: ./push-to-another-repo
        with:
          source: test-dir/date.txt
          destination_repo_name: gadaniyati/actions
          destination_branch: test-commit-message
          commit_message: custom commit message for content push (${{ github.sha }})
          access_key: ${{ secrets.ACCESS_KEY }}

      - name: test for no changes / nothing to commit
        uses: ./push-to-another-repo
        with:
          source: test-dir/date.txt
          destination_repo_name: gadaniyati/actions
          destination_branch: test-commit-message
          commit_message: custom commit message for content push (${{ github.sha }})
          access_key: ${{ secrets.ACCESS_KEY }}
